package com.damdamdeo.eventdataspreader.event.infrastructure.consumer;

import com.damdamdeo.eventdataspreader.event.api.consumer.AggregateRootEventConsumedRepository;

public interface KafkaAggregateRootEventConsumedRepository extends AggregateRootEventConsumedRepository<KafkaInfrastructureMetadata> {
}
